title: Pwn-Solo
tagline: Security Research & CTF
description: Security researcher, vulnerability analysis, and exploitation
author:
  name: Hrishikesh Pankaj
url: https://pwn-solo.github.io
baseurl: ""
paginate: 10
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
nav:
  - title: Posts
    url: /archive
  - title: About
    url: /about
